# Site
repository: psm651/psm651.github.io

# Personal info
name: 박성민
title: 백엔드 개발자
email: psm651@naver.com
website: https://shutcoding.tistory.com

# Additional icon links
additional_links:
  - title: Tech Blog
    icon: fab fa-blogger
    url: https://shutcoding.tistory.com

# Social links
github_username: psm651

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Java,PHP 기반의 5년차 백엔드 개발자 박성민입니다.  \
  문제를 해결하여 비즈니스 성장에 기여하는 일을 최우선으로 합니다. 빠른 개발은 역설적이게도 바른 개발임을 느껴 서비스를 심도있게 분석/설계하고, 테스트코드를 작성하여 디버깅 최소화 및 리팩토링시간 단축을 위한 역량을 쌓고자 노력중입니다.
  개발에 집중하기 위해 **반복되는 일을 자동화하고, 비효율적인 프로세스를 개선하여 개발 생산성을 높이는 일**을 좋아합니다.  \
  세상에 신은 없다고 믿기에 배포 하며 기도 하지 않고, 항상 최악의 상황을 가정해 발생할 수 있는 장애를 도출하고, 장애 처리 결과는 추측을 넘어 데이터로 확인하기 위해 노력합니다.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag